// #include <bits/stdc++.h>
// using namespace std;

// int a[15][15];

// int main()
// {
//     int n;
//     cin>>n;

//     for (int i = 0; i < n; i++)
//     {
//         for (int j = 0; j < n ; j++)
//         {
//             cin>>a[i][j];
//         }
//     }

//     for (int i = 1; i < n; i++)
//     {
//         for (int j = 0; j < i; j++)
//         {
//             if (a[i][j] != 0)
//             {
//                 cout<<"NO";
//                 return 0;
//             }
//         }
//     }

//     cout<<"YES";

//     return 0;
// }